WITH TMP AS (
    SELECT ID
          ,RANK() OVER 
           (ORDER BY SIZE_OF_COLONY DESC) AS COLONY_RANK
    FROM ECOLI_DATA
),
TOTAL_CNT AS (
    SELECT COUNT(ID) AS CNT
      FROM ECOLI_DATA
)
SELECT A.ID
     , CASE
            WHEN B.COLONY_RANK / C.CNT <= 0.25 THEN 'CRITICAL'
            WHEN B.COLONY_RANK / C.CNT <= 0.5 THEN 'HIGH'
            WHEN B.COLONY_RANK / C.CNT <= 0.75 THEN 'MEDIUM'
            ELSE 'LOW'
        END
        AS COLONY_NAME
    # , TMP.COLONY_RANK
    # , COUNT(TMP.ID)
  FROM ECOLI_DATA A
  JOIN TMP B
    ON A.ID = B.ID
  # GROUP BY A.ID
 CROSS JOIN TOTAL_CNT C
 ORDER BY A.ID ASC;





# WITH TOTAL_CNT AS (
#     SELECT ID
#       FROM ECOLI_DATA
#      ORDER BY ID DESC
#      LIMIT 1
# )
# SELECT * FROM TOTAL_CNT;