-- 코드를 입력하세요
SELECT A.REST_ID
     , A.REST_NAME
     , A.FOOD_TYPE
     , A.FAVORITES
     , A.ADDRESS
     , ROUND(AVG(B.REVIEW_SCORE), 2) AS AVERAGE
FROM REST_INFO A
JOIN REST_REVIEW B
ON (A.REST_ID = B.REST_ID)
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY AVERAGE DESC, A.FAVORITES DESC;

# SELECT * FROM REST_INFO;
# SELECT * FROM REST_REVIEW;