-- 코드를 작성해주세요
SELECT B.ITEM_ID
     , C.ITEM_NAME
     , C.RARITY
  FROM ITEM_INFO A
  JOIN ITEM_TREE B
    ON A.ITEM_ID = B.PARENT_ITEM_ID
  JOIN ITEM_INFO C
    ON C.ITEM_ID = B.ITEM_ID
 WHERE A.RARITY = 'RARE'
 ORDER BY B.ITEM_ID DESC;