SELECT DISTINCT C.ID
     , A.GENOTYPE
     , B.GENOTYPE AS PARENT_GENOTYPE
  FROM ECOLI_DATA A
  LEFT JOIN ECOLI_DATA B
    ON (A.PARENT_ID = B.ID)
  JOIN ECOLI_DATA C
    ON (A.ID = C.ID)
 WHERE A.GENOTYPE & B.GENOTYPE = B.GENOTYPE;