-- 코드를 입력하세요
SELECT  A.FLAVOR
  FROM  ICECREAM_INFO A
 INNER JOIN
  (SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF WHERE TOTAL_ORDER >= 3000) B
  ON A.FLAVOR = B.FLAVOR
 WHERE A.INGREDIENT_TYPE = 'fruit_based';