WITH C AS (
    SELECT MAX(A.LENGTH) AS LENGTH
         , B.FISH_TYPE
         , B.FISH_NAME
      FROM FISH_INFO AS A
      JOIN FISH_NAME_INFO AS B
        ON A.FISH_TYPE = B.FISH_TYPE
     GROUP
        BY B.FISH_TYPE, B.FISH_NAME
)

SELECT A.ID
     , C.FISH_NAME
     , C.LENGTH
  FROM FISH_INFO AS A
  JOIN C AS C
    ON A.FISH_TYPE = C.FISH_TYPE AND A.LENGTH = C.LENGTH
 ORDER
    BY A.ID ASC;
  